---
fail_fast: true
exclude: \.ply$
repos:
  - repo: local
    hooks:
      - id: cargo-nextest
        name: Cargo Nextest
        entry: cargo nextest run
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-check
        name: Cargo Check
        entry: cargo check
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-clippy
        name: Cargo Clippy (with warnings)
        entry: cargo clippy -- -D warnings
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-fmt-check
        name: Cargo Format (check)
        entry: cargo +nightly fmt -- --check
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-clippy-fix
        name: Cargo Clippy
        entry: cargo clippy --fix
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-push]

      - id: cargo-fmt
        name: Cargo Format
        entry: cargo +nightly fmt
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-push]

