---
fail_fast: true
exclude: \.ply$
repos:
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.37.0
    hooks:
      - id: talisman-commit
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.91.1
    hooks:
      - id: trufflehog
  - repo: local
    hooks:
      - id: cargo-nextest
        name: Cargo Nextest
        entry: cargo nextest run --profile ci --workspace
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-check
        name: Cargo Check
        entry: cargo check
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-clippy
        name: Cargo Clippy (with warnings)
        entry: cargo clippy --all-targets --all-features -- -D warnings
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-fmt-check
        name: Cargo Format (check)
        entry: cargo fmt -- --check
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-fix
        name: Cargo Fix
        entry: cargo fix --all-targets --all-features
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-push]

      - id: cargo-clippy-fix
        name: Cargo Clippy
        entry: cargo clippy --all-targets --all-features --fix -- -D warnings
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-push]

      - id: cargo-fmt
        name: Cargo Format
        entry: cargo fmt
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-push]

