---
fail_fast: true
exclude: \.ply$
repos:
  - repo: local
    hooks:
      - id: cargo-test
        name: Cargo Test
        entry: cargo test
        pass_filenames: false
        language: system
        types: [rust]

      - id: cargo-check
        name: Cargo Check
        entry: cargo check
        pass_filenames: false
        language: system
        types: [rust]

      - id: cargo-clippy
        name: Cargo Clippy (with warnings)
        entry: cargo clippy -- -D warnings
        pass_filenames: false
        language: system
        types: [rust]

      - id: cargo-fmt
        name: Cargo Format
        entry: cargo fmt -- --check
        pass_filenames: false
        language: system
        types: [rust]

