[package]
name = "tdd-playground"
version = "0.1.0"
authors = ["Eleanore Young"]

[workspace]

[dependencies]
log = "^0.4.1"
fern = "^0.5.4"
ecs = {path = "ecs"}
engine = {path = "engine"}
game = {path = "game"}
