[package]
name = "rootspace"
version = "0.1.0"
authors = ["Eleanor Young <developer@nausicaea.net>"]
edition = "2021"

[lib]
name = "rootspace"

[[bin]]
name = "ply-loader"
path = "src/bin/ply_loader.rs"

[[example]]
name = "wgpu_playground"

[[example]]
name = "create_scene"

[[example]]
name = "engine_test"

[[example]]
name = "async_std_playground"

[features]
dbg-gfx = []
dbg-loop = []

[dependencies]
winit = { version = "0.29", features = ["serde"] }
wgpu = { version = "0.19", features = ["serde", "trace", "replay"] }
bytemuck = { version = "1.0", features = [ "derive" ] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
ctrlc = { version = "3.0.0", features = ["termination"] }
clap = { version = "4.0.0", features = ["derive"] }
directories = "5.0"
ciborium = "^0.2.0"
lazy_static = "1.0"
regex = "1.0"
downcast-rs = "1.0.0"
nom = "7.0.0"
either = "1.0"
log = "0.4.14"
thiserror = "1.0.0"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"
anyhow = { version = "1.0.0" }
num-traits = "0.2.14"
approx = "0.5.0"
async-std = "1.12.0"

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
env_logger = "0.11"
tempfile = "3.0.1"
serde_test = "1.0.126"
proptest = "1.0.0"
proptest-derive = "0.4.0"
cgmath = "0.18.0"
rstest = "0.18.2"
