[package]
name = "tdd-playground"
version = "0.1.0"
authors = ["Eleanore Young"]

[workspace]

[dependencies]
clap = "^2.31.2"
log = "^0.4.1"
fern = "^0.5.5"
ecs = {path = "ecs"}
hierarchy = {path = "hierarchy"}
engine = {path = "engine"}
game = {path = "game"}

[dev-dependencies]
assertions = {path = "assertions"}
