[workspace]
resolver = "2"
members = [
  "crates/assam",
  "crates/ecs",
  "crates/file-manipulation",
  "crates/forward-ref",
  "crates/glamour",
  "crates/griffon",
  "crates/plyers",
  "crates/rootspace",
  "crates/rose-tree",
  "crates/urn",
]
exclude = [
  "crates/fuzz",
]

[profile.release]
panic = "abort"

