[workspace]
resolver = "2"
members = [
    "try-default",
    "file-manipulation",
    "ecs",
    "engine",
    "rootspace",
    "rose-tree",
    "glamour",
    #"ply",
    "plyers",
    "plynth",
    "forward-ref",
]
