[package]
name = "ygdrasil"
version = "0.1.1"
authors = ["Eleanore Young"]
edition = "2018"

[workspace]

[dependencies]
clap = { version = "^2.0.0", default-features = false }
anyhow = "^1.0.0"
thiserror = "^1.0.0"
log = "^0.4.1"
fern = "^0.5.5"
affine-transform = { path = "affine-transform" }
ply = { path = "ply" }
hierarchy = { path = "hierarchy" }
ecs = { path = "ecs" }
engine = { path = "engine" }
rootspace = { path = "rootspace" }
pacman = { path = "pacman" }
