[package]
name = "tdd-playground"
version = "0.1.0"
authors = ["Eleanore Young"]

[workspace]

[features]
wsl = []

[dependencies]
clap = "^2.31.2"
combine = "^3.5.1"
log = "^0.4.1"
fern = "^0.5.5"
engine = {path = "engine"}
game = {path = "game"}

[dev-dependencies]
assertions = {git = "https://gitlab.com/nausicaea/assertions.git"}
