[package]
name = "tdd-playground"
version = "0.1.0"
authors = ["Eleanore Young"]

[workspace]

[features]
wsl = []

[dependencies]
clap = "^2.31.2"
log = "^0.4.1"
fern = "^0.5.5"
affine-transform = {path = "affine-transform"}
ecs = {path = "ecs"}
engine = {path = "engine"}
hierarchy = {path = "hierarchy"}
game = {path = "game"}

[dev-dependencies]
assertions = {path = "assertions"}
