[workspace]
edition = "2021"
resolver = "2"
members = [
    "try-default",
    "file-manipulation",
    "ply",
    "ecs",
    "engine",
    "rootspace",
    "rose-tree",
    "glamour",
    "forward-ref",
]
