[package]
name = "rootspace"
version = "0.1.0"
authors = ["Eleanor Young <developer@nausicaea.net>"]
edition = "2021"

[features]
editor = []
dbg-gfx = []
dbg-loop = []
test-flaky = []

[profile.release]
panic = "abort"

[dependencies]
winit = { version = "0.29", features = ["serde"] }
wgpu = { version = "0.19", features = ["serde", "trace", "replay"] }
bytemuck = { version = "1.0", features = [ "derive" ] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
ctrlc = { version = "3.0.0", features = ["termination"] }
clap = { version = "4.0.0", features = ["derive"] }
directories = "5.0"
ciborium = "^0.2.0"
lazy_static = "1.0"
regex = "1.0"
downcast-rs = "1.0.0"
nom = "7.0.0"
either = "1.0"
thiserror = "1.0.0"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"
anyhow = { version = "1.0.0" }
num-traits = "0.2.14"
approx = "0.5.0"
async-trait = "0.1.77"
parking_lot = { version = "0.12.1", features = ["send_guard"] }
futures = { version = "0.3.30", default-features = false, features = ["std"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros", "net", "fs", "io-util", "sync", "tracing"] }
tarpc = { version = "0.34.0", features = ["serde-transport-bincode", "tcp", "serde-transport"] }
humantime = "2.1.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
console-subscriber = "0.2.0"
itertools = "0.12.1"

[dev-dependencies]
tempfile = "3.0.1"
serde_test = "1.0.126"
proptest = "1.0.0"
proptest-derive = "0.4.0"
rstest = "0.18.2"
criterion = "0.5.1"
cgmath = "0.18.0"
nalgebra = "0.32.4"
mutants = "0.0.3"

[lib]
name = "rootspace"

[[bin]]
name = "ply_loader"

[[bin]]
name = "rpc_client"

[[bin]]
name = "rootspace"

[[example]]
name = "wgpu_playground"

[[example]]
name = "create_scene"

[[bench]]
name = "plyers_benchmarks"
harness = false
