[workspace]
resolver = "2"
members = [
  "ecs",
  "file-manipulation", 
  "forward-ref",
  "glamour",
  "plyers",
  "rootspace",
  "rose-tree", 
  "urn",
]
exclude = [
  "fuzz",
]

[profile.release]
panic = "abort"

