[package]
name = "engine"
version = "0.1.0"
authors = ["Eleanore Young"]

[features]
diagnostics = []
mock = ["ecs/mock"]
wsl = []

[dependencies]
approx = "^0.3.0"
bitflags = "^1.0.3"
clap = "^2.0.0"
ctrlc = {version = "^3.0.0", features = ["termination"]}
failure = "^0.1.1"
glium = "^0.22.0"
image = "^0.20.0"
log = "^0.4.1"
nalgebra = "^0.16.0"
num-traits = "^0.2.6"
rusttype = {version = "^0.7.2", features = ["gpu_cache"]}
unicode-normalization = "^0.1.5"
affine-transform = {git = "https://gitlab.com/nausicaea/affine-transform.git"}
hierarchy = {git = "https://gitlab.com/nausicaea/hierarchy.git"}
ecs = {git = "https://gitlab.com/nausicaea/ecs.git"}
ply = {git = "https://gitlab.com/nausicaea/ply.git"}

[dev-dependencies]
assertions = {git = "https://gitlab.com/nausicaea/assertions.git"}
tempfile = "^3.0.1"
quickcheck = "^0.7.1"
ecs = {git = "https://gitlab.com/nausicaea/ecs.git", features = ["mock"]}
