[package]
name = "engine"
version = "0.1.0"
authors = ["Eleanore Young"]

[dependencies]
bitflags = "^1.0.1"
failure = "^0.1.1"
log = "^0.4.1"
glium = "^0.20.0"
winit = "^0.11.3"
ecs = {path = "../ecs"}

[dev-dependencies]
tempfile = "^2.2.0"
quickcheck = "^0.6.2"
