[package]
name = "engine"
version = "0.1.0"
authors = ["Eleanore Young"]

[dependencies]
bitflags = "^1.0.3"
failure = "^0.1.1"
log = "^0.4.1"
glium = "^0.21.0"
nalgebra = "^0.15.0"
hierarchy = {path = "../hierarchy"}
ecs = {path = "../ecs"}

[dev-dependencies]
assertions = {path = "../assertions"}
approx = "^0.2.0"
tempfile = "^3.0.1"
quickcheck = "^0.6.2"
