[package]
name = "engine"
version = "0.1.0"
authors = ["Eleanore Young"]

[features]
diagnostics = []
wsl = []
mock = []

[dependencies]
bitflags = "^1.0.3"
failure = "^0.1.1"
glium = "^0.22.0"
image = "^0.20.0"
log = "^0.4.1"
nalgebra = "^0.16.0"
rusttype = {version = "^0.7.2", features = ["gpu_cache"]}
affine-transform = {path = "../affine-transform"}
hierarchy = {path = "../hierarchy"}
ecs = {path = "../ecs"}
ply = {path = "../ply"}

[dev-dependencies]
assertions = {path = "../assertions"}
approx = "^0.3.0"
tempfile = "^3.0.1"
quickcheck = "^0.7.1"
ecs = {path = "../ecs", features = ["mock"]}
