[package]
name = "engine"
version = "0.1.0"
authors = ["Eleanore Young"]
edition = "2018"

[features]
diagnostics = []
mock = []
wsl = []

[dependencies]
bitflags = "^1.0.3"
clap = {version = "^2.0.0", default-features = false}
ctrlc = {version = "^3.0.0", features = ["termination"]}
failure = "^0.1.1"
glium = "^0.25.0"
image = {version = "^0.21.0", default-features = false, features = ["png_codec"]}
log = "^0.4.1"
nalgebra = "^0.18.0"
num-traits = "^0.2.6"
rusttype = {version = "^0.7.2", features = ["gpu_cache"]}
unicode-normalization = "^0.1.5"
affine-transform = {git = "https://gitlab.com/nausicaea/affine-transform.git"}
hierarchy = {git = "https://gitlab.com/nausicaea/hierarchy.git"}
ecs = {path = "../ecs"}
ply = {git = "https://gitlab.com/nausicaea/ply.git"}

[dev-dependencies]
approx = "^0.3.0"
tempfile = "^3.0.1"
quickcheck = {version = "^0.8.2", default-features = false}
