[package]
name = "engine"
version = "0.1.0"
authors = ["Eleanore Young"]

[dependencies]
log = "^0.4.1"
failure = "^0.1.1"
ecs = {path = "../ecs"}

[dev-dependencies]
tempfile = "^2.2.0"
quickcheck = "^0.6.2"
