[package]
name = "engine"
version = "0.1.0"
authors = ["Eleanore Young"]

[dependencies]
bitflags = "^1.0.1"
failure = "^0.1.1"
log = "^0.4.1"
glium = "^0.21.0"
vulkano = "^0.9.0"
winit = "^0.11.3"
hierarchy = {path = "../hierarchy"}
ecs = {path = "../ecs"}

[dev-dependencies]
assertions = {path = "../assertions"}
tempfile = "^2.2.0"
quickcheck = "^0.6.2"
