[package]
name = "try-default"
version = "0.1.0"
authors = ["Eleanore Young <developer@nausicaea.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.40"
