[package]
name = "plyers"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
nom = "7.1.1"
either = "1.0"
file-manipulation = { path = "../file-manipulation" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
