[package]
name = "ecs"
version = "0.5.0"
authors = ["Eleanore Young"]
description = "The ecs library provides facilities to build an Entity-Component-System architecture"
edition = "2018"

[features]
diagnostics = ["typename"]

[dependencies]
hibitset = {version = "^0.6.0", default-features = false}
downcast-rs = "^1.0.0"
typename = {version = "^0.1.0", optional = true}
