[package]
name = "ecs"
version = "0.5.0"
authors = ["Eleanore Young"]
description = "The ecs library provides facilities to build an Entity-Component-System architecture"
edition = "2018"

[features]
diagnostics = []

[dependencies]
downcast-rs = "^1.0.0"
log = "^0.4.1"
serde = { version = "^1.0.0", features = ["derive"] }
serde_json = "^1.0.0"
typename = "^0.1.0"

[dev-dependencies]
serde_test = { version = "^1.0.0" }
proptest = "^0.9.0"
