[package]
name = "ecs"
version = "0.4.0"
authors = ["Eleanore Young"]
description = "The ecs library provides facilities to build an Entity-Component-System architecture"
edition = "2018"

[dependencies]
hibitset = {version = "^0.6.0", default-features = false}
mopa = "^0.2.2"
