[package]
name = "ecs"
version = "0.1.0"
authors = ["Eleanore Young"]

[dependencies]
log = "^0.4.1"
failure = "^0.1.1"
bitflags = "^1.0.1"
snowflake = "^1.3.0"

[dev-dependencies]
quickcheck = "^0.6.2"
