[package]
name = "ecs"
version = "0.5.0"
authors = ["Eleanore Young"]
description = "The ecs library provides facilities to build an Entity-Component-System architecture"
edition = "2018"

[features]
diagnostics = []

[dependencies]
hibitset = { version = "^0.6.0", default-features = false }
downcast-rs = "^1.0.0"
typename = "^0.1.0"
serde = { version = "^1.0.0", features = ["derive"] }
serde_json = { version = "^1.0.0" }
failure = "^0.1.1"

[dev-dependencies]
serde = { version = "^1.0.0", features = ["derive"] }
serde_test = { version = "^1.0.0" }
proptest = "^0.9.0"
