[package]
name = "ecs"
version = "0.3.1"
authors = ["Eleanore Young"]
description = "The ecs library provides facilities to build an Entity-Component-System architecture"
repository = "https://gitlab.com/nausicaea/ecs.git"
edition = "2018"

[features]
mock = []

[dependencies]
bitflags = "^1.0.0"
failure = "^0.1.1"
snowflake = "^1.3.0"

[dev-dependencies]
quickcheck = {version = "^0.7.1", default-features = false}
