[package]
name = "ply"
version = "0.1.0"
authors = ["Eleanore Young <youngelliecaitlin@gmail.com>"]

[dependencies]
combine = "^3.5.1"
num-traits = "^0.2.5"

[dev-dependencies]
assertions = {path = "../assertions"}
